{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    {{- include "obtrace-sdk-integration.labels" . | nindent 4 }}
type: Opaque
stringData:
  OBTRACE_API_KEY: {{ .Values.secret.apiKey | quote }}
{{- end }}
